### ISSUE TITLE
"Once per bar close" option doesn't get selected consistently 

### ISSUE THREAD

**Issue by dtrce** [alleyway/add-tradingview-alerts-tool#115]
I'm running add-alerts with the following alert config but for some reason "Once per bar close" option doesn't always get selected. Sometimes it creates an alert with "Only once" which is the default option. 

```
alert:
  condition: # tertiary/quaternary rows might not exist for your indicator. If not remove those values
    primaryLeft: RSI
    primaryRight:
    secondary: Greater Than
    tertiaryLeft: Value
    tertiaryRight: 30    
  option: Once Per Bar Close

```
