### ISSUE TITLE
TradingView changed alert layout and script is encountering issue:

### ISSUE THREAD

**Issue by Patrik-Tkacik** [alleyway/add-tradingview-alerts-tool#166]
All was well until today, they moved the message to a new tab and its unable to set prices:

ERROR  Unable to find dropdown xpath target for primaryLeft/secondary. Make sure chart layout is SAVED with an indicator that contains/matches this: Entering Channel

config:
```
files:
  input: tickers.csv

tradingview:
  # The chart which has the indicator you'd like to use
  chartUrl: https://www.tradingview.com/chart/xxx/
  # (optional) set the chart interval before adding symbols, otherwise interval of last saved chart is used
  # examples: 1s | 30s | 1m | 15m | 1H | 1D | 1W      # NOTE: '1H,4H' to add alerts across multiple intervals
  interval: 1m
  # Optionally supply login details or login manually once and restart script
  #username: 
  #password: 
alert:
  condition:
    primaryLeft:
    primaryRight:
    secondary: Entering Channel
    tertiaryRight: "{{priceHigher}}"
    quaternaryRight: "{{priceLower}}"
  actions:
    notifyOnApp: false
    showPopup: 
    sendEmail: false
    webhook:
      enabled: true
      url: ".../hooks/xxx"
  # alert name is optional - can override in csv if desired and use {{symbol|instrument|quote_asset}}
  # name: MI dev3 for {{instrument}} {{quote_asset}}
  # indentation matters! {{quote_asset}} and {{instrument}} are swapped out for quote asset(eg. USDT) and the base token or instrument (eg. 'BTC')
  name: "{{date}} - MW level getting close"
  message: >
   {{message}}
```
