### ISSUE TITLE
ERROR  Unable to find any inputs for 'tertiaryLeft' for configured value: 'Value'

### ISSUE THREAD

**Issue by minhphuc429** [alleyway/add-tradingview-alerts-tool#167]
Error log

```
 ERROR  Unable to find any inputs for 'tertiaryLeft' for configured value: 'Value'                                                                                                                      5:36:05 PM

ℹ Adding symbol: CAPITALCOM:EURUSD | Instrument: [object Object] Quote Asset: [object Object]                                                                                                          5:36:05 PM
```

Example alert

<img width="465" alt="Image" src="https://github.com/user-attachments/assets/96e2ef4b-ad8b-4762-96b0-cf12b3a20aa8" />

Example config

```
alert:
  condition: # tertiary/quaternary rows might not exist for your indicator. If not remove those values
    primaryLeft: /^Stoch RSI.*$/
    primaryRight: K
    secondary: Inside Channel
    tertiaryLeft: Value
    tertiaryRight: 60.00
    quaternaryLeft: Value
    quaternaryRight: 50.00
  option: Once Per Bar Close
```
