### ISSUE TITLE
Condition selection & quaternary (left/right)

### ISSUE THREAD

**Issue by m4ybee** [alleyway/add-tradingview-alerts-tool#46]
On one of my indicators to obtain the correct alert i need to select the Pair in the condition section, not the indicator name. The indicator is selected in the tertiary & quaternary  sections. 

A couple of questions:

1)  Can i select the pair in condition section even though it changes dynamically with each alert created (as per the CSV pair list file) when the tool is run?  Is it even possible or can the config.yml file be setup to just select the drop down position in condition not the pair name which in my case would be 1? Unfortunately the default sets to indicator name
![Screenshot 2021-05-06 at 11 37 07](https://user-images.githubusercontent.com/83712445/117285718-3be6b180-ae60-11eb-9ab7-df9c8e02033d.png)
.

2) Can i edit the config.yml file to have a quaternary left  / right ? As you can see in the screenshot i wish to alert entering a channel which needs Upper and Lower bounds

Condition: Pair (current - position 1)
Secondary: Entering Channel
Tertiary: Left = Indicator Right = Indicator
Quaternary: Left = Indicator Right = Indicator

Thanks for your help and btw awesome job.

**Comment by mlake** [comment]
Hi again - pointing out a couple flaws I didn't realize..

1) Can you help me understand more why you need to select a particular position? That would be a tad brittle.
Otherwise, I could modify the tool so each condition can have dynamic placeholders..
For example, consider the following where {{symbol}} would be replaced with "MATICUSDTPERP" from the .csv file:
```yaml
alert:
  condition:
    primaryLeft: "{{symbol}}"
    primaryRight: Volume
    secondary: Crossing
    tertiaryLeft: "BitMEX Funding and Premium Index"
    tertiaryRight: Funding Rate
```

2) I had no idea that there could be even more inputs...gonna have go back to the drawing board here and work on a solution...maybe I could create a quick "quaternary" solution, but now that starts to sounds weirder than "tertiary"

**Comment by m4ybee** [comment]
Hi there, 

1) the reason for selecting a particular position is because the condition has a drop down and shows the pair and indicators. For my particular case i need to chose the pair which is in the first position (blacked out ones are indicator names). Your suggestion i think could work. 
![Screenshot 2021-05-06 at 13 32 18](https://user-images.githubusercontent.com/83712445/117299204-28dbdd80-ae70-11eb-83a1-462a39245b16.png)

2) Yeah quaternary does sound weird.. was going for consistency lol. I don't have experience in programming these things but if its not too hard a quick 4th option would be good.

**Comment by mlake** [comment]
So it turns out you can actually just leave "primaryLeft" blank and the script skips over it..

was able to add "quaternary" left and right (will never remember how to spell that!)

Grab the update (from your alerts-home directory):

```
tradingview-alerts-home $ npm install @alleyway/add-tradingview-alerts-tool@1.8.0
```
make your config look something like this:
```yaml
alert:
  condition:
    primaryLeft:
    primaryRight:
    secondary: Entering Channel
    tertiaryLeft: Value
    tertiaryRight: 5000
    quaternaryLeft: Value
    quaternaryRight: 4000
```
