### ISSUE TITLE
Unable to find Xpath target for secondary

### ISSUE THREAD

**Issue by phl3x0r** [alleyway/add-tradingview-alerts-tool#56]
Any way to resolve this?
```
» Searching potential dropdown xpath of secondary                                                                                                                                                                                             16:36:02  
» ...selector: //*[@class='tv-control-fieldset__value tv-alert-dialog__fieldset-value js-condition-operator-input-wrap']/*[@class='tv-control-select__wrap tv-dropdown-behavior tv-control-select--size_small' and 1]/span[@class='tv-control-select__control tv-dropdown-behavior__button' and 1]

 ERROR  Unable to find Xpath target for primaryLeft/secondary which doesn't have inputs, so won't even try                                                                                                                                    16:36:05  

  at performActualEntry (/Q:/Trading/node/sandbox/tradingview-alerts-home/node_modules/@alleyway/add-tradingview-alerts-tool/src/service/tv-page-actions.ts:213:32)
  at configureSingleAlertSettings (/Q:/Trading/node/sandbox/tradingview-alerts-home/node_modules/@alleyway/add-tradingview-alerts-tool/src/service/tv-page-actions.ts:231:13)
  at addAlert (/Q:/Trading/node/sandbox/tradingview-alerts-home/node_modules/@alleyway/add-tradingview-alerts-tool/src/service/tv-page-actions.ts:331:5)
  at addAlertsMain (/Q:/Trading/node/sandbox/tradingview-alerts-home/node_modules/@alleyway/add-tradingview-alerts-tool/src/add-alerts.ts:219:9)
  at Command.<anonymous> (/Q:/Trading/node/sandbox/tradingview-alerts-home/node_modules/@alleyway/add-tradingview-alerts-tool/src/cli.ts:67:13)
```

**Comment by mlake** [comment]
Config file?

**Comment by phl3x0r** [comment]
```yaml
files:
  input: ftx_perp_pairs.csv
  exclude: blacklist.csv
tradingview:
  # The chart which has the indicator you'd like to use
  chartUrl: https://www.tradingview.com/chart/xxxxxxxx/
  # (optional) set the chart interval before adding pairs, otherwise interval of last saved chart is used
  # examples: 1s | 30s | 1m | 15m | 1h | 1D | 1M
  interval: 5m
  # Optionally supply login details or login manually once and restart script
  username: xxxxxxxx
  password: xxxxxxxx
alert:
  condition:
    primaryLeft: xxxxxxxx
    primaryRight:
    secondary: xxxxxxxx
    tertiaryLeft:
    tertiaryRight:
    quaternaryLeft:
    quaternaryRight:
  option: Once Per Bar Close
  actions:
    notifyOnApp: false
    showPopup: false
    sendEmail: false
    webhook:
      enabled: true
      url: "http://x.x.x.x/y"
  # alert name is optional - can override in csv if you add a "name" column. can use {{symbol|base|quote}}
  # name: "MI dev3 for {{base}} {{quote}}"
  # indentation matters! {{quote}} and {{base}} are swapped out for quote asset(eg. USDT) and the base (eg. BTC)
  message: >
    {
      "symbol": "{{ticker}}",
      "exchange": "{{exchange}}",
      "price": {{close}},
      "volume": {{volume}},
      "buy": {{plot_0}},
      "sell": {{plot_2}},
      "stongbuy": {{plot_1}},
      "strongsell": {{plot_3}},
      "source": "xxxxxxxx",
      "timeframe": {{interval}}, 
      "timealert": "{{timenow}}"
    }
```
