### ISSUE TITLE
Does not update "option" field with "Once Per Bar Close"

### ISSUE THREAD

**Issue by cmartin81** [alleyway/add-tradingview-alerts-tool#73]
I've been using this tool quite a lot and it works like a charm. Except for today. I tried setting the option with the following config

```
alert:
  condition:
    primaryLeft: foo bar
    primaryRight: BUY Signal
    secondary: Greater Than
    tertiaryLeft: Value
    tertiaryRight: "0"
  option: Once Per Bar Close
```

But it did not set this option at all when running live. I had to do this manually after all the alerts were created. The only different I've been doing here is adding a " around the value of tertiaryRight ( "0" )
