### ISSUE TITLE
How to add multiple alerts to one pair

### ISSUE THREAD

**Issue by NormanBenbrahim** [alleyway/add-tradingview-alerts-tool#80]
Great tool, thanks for making it open source. 

Was wondering if there's a way to add multiple alerts to a single pair. For example, my `ftx_perp_pairs.csv` file contains one instrument (let's say FTX: 1INCHPERP)

I want to add multiple alerts in a single run, is that possible? I get ` ERROR  Map keys must be unique; "alert" is repeated` when I try the following `config.yml` file:

```
files:
  input: ftx_perp_pairs.csv
  exclude: blacklist.csv
tradingview:
  # The chart which has the indicator you'd like to use
  chartUrl: https://www.tradingview.com/chart/mychart
  # Optionally supply login details or login manually once and restart script
  username: myusername
  password: mypassword
alert:
  condition: # tertiary/quaternary rows might not exist for your indicator. If not remove those values
    primaryLeft: 1INCHPERP
    secondary: Crossing
    tertiaryLeft: Value
    tertiaryRight: 4000
  option: Only Once
  actions:
    notifyOnApp: true
    showPopup: true
    sendEmail: false
    webhook:
      enabled: false
  message: "1INCHPERP short stopped out"
alert:
  condition: 
    primaryLeft: 1INCHPERP
    secondary: Crossing
    tertiaryLeft: Value
    tertiaryRight: 3800
  option: Only Once
  actions:
    notifyOnApp: true
    showPopup: true
    sendEmail: false
    webhook:
      enabled: false
  message: "1INCHPERP TP1"
```

Do I need to build out separate yaml files each time i want to do this?
